[theme]
base = "dark"
primaryColor = "#E5484D"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
